import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider";
import { Suspense } from "react";
import Navigation from "../components/Navigation";
import { SidebarProvider, SidebarTrigger } from "../components/ui/sidebar";
import { SidebarNav } from "../components/sidebar/SidebarNav";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Nextjs App",
	authors: [{ name: "Jesus Torres", url: "https://torresjdev.github.io/" }],
	description: "Generated by create next app",
	icons:
		"https://torresjdev.github.io/Nextjs-Asset-Host/assets/icons/dev/dev-md.svg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`gradient-background ${inter.className}`}>
				<div className="gradient-background"></div>
				<Navigation />
				<ThemeProvider
					enableSystem={false}
					disableTransitionOnChange
					attribute="class"
					defaultTheme="dark"
				>
					<SidebarProvider>
						<div className="flex max-h-full max-w-full w-full">
							<aside>
								<SidebarNav />
							</aside>
							<main className="w-full mx-2 md:ml-[10px] md:px-2 mt-24 sm:mt-20 md:mt-16 flex flex-1 max-h-full p-3 md:p-1">
								<SidebarTrigger />
								<section className="min-h-[92vh] w-11/12 flex flex-col mx-auto align-middle">
									<Suspense
										fallback={<div className="animate-spin">Loading...</div>}
									>
										{children}
									</Suspense>{" "}
								</section>
							</main>
						</div>
					</SidebarProvider>
				</ThemeProvider>
				<Footer />
			</body>
		</html>
	);
}
