import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider";
import { Suspense } from "react";
import Navigation from "./components/Navigation";
import { SidebarProvider, SidebarTrigger } from "./components/ui/sidebar";
import { AppSidebar } from "./components/AppSidebar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Nextjs App",
	authors: [{ name: "Jesus Torres", url: "https://torresjdev.github.io/" }],
	description: "Generated by create next app",
	icons:
		"https://torresjdev.github.io/Nextjs-Asset-Host/assets/icons/dev/dev-md.svg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`gradient-background ${inter.className}`}>
				<div className="gradient-background"></div>
				<Navigation />
				<ThemeProvider
					enableSystem={false}
					disableTransitionOnChange
					attribute="class"
					defaultTheme="dark"
				>
					<SidebarProvider>
						<div className="flex max-h-full">
							<aside>
								<AppSidebar />
							</aside>
							<main className="max-w-full ml-[10px] md:px-2 mt-16 flex flex-1 max-h-[50rem]">
								<SidebarTrigger />
								<Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
							</main>
						</div>
					</SidebarProvider>
				</ThemeProvider>
				<Footer />
			</body>
		</html>
	);
}
