name: Build and Deploy Next.js App

on:
  push:
    branches: [main, repo-merge-donations-jar]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Site Configuration
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      NEXT_PUBLIC_GITHUB_USERNAME: ${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }}
      NEXT_PUBLIC_WAKATIME_USERNAME: ${{ secrets.NEXT_PUBLIC_WAKATIME_USERNAME }}

      # Stripe Configuration
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}

      # Coinbase Configuration
      COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests (if available)
        run: npm test --if-present
        continue-on-error: true
